### ISSUE TITLE
Sites View

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#24]
Add an admin page that displays all sites in the instance similar to the Perspective app, see:
https://clas-incubator-wp.uncc.edu/perspective/index.php

Priorities:
*filter by # of posts
*filter by active/inactive in time period (days, weeks, months)
*filter by admin

Sorting:
default sort by the site with the most recent post

**Comment by cbarto11** [comment]
d3095a23c38d761fc75e92387d72700a7a16b6b0
