### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#26]
When activating the org hub plugin on a new instance, the following error results:
Fatal error: Access level to OrgHub_SitesListTable::get_sortable_columns() must be public (as in class WP_List_Table) in /Users/alex/Sites/clas-pages/wp-content/plugins/organization-hub/classes/sites-list-table.php on line 23

**Comment by cbarto11** [comment]
d3095a23c38d761fc75e92387d72700a7a16b6b0
