### ISSUE TITLE
Add bulk actions

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#32]
Add bulk actions for:
* delete
* archive

Add classes to make it easier to add custom bulk actions such as:
* change theme
* change site admin
*

**Comment by cbarto11** [comment]
aa20543a469ff643c9e9dd6426061add6964bcd5

**Comment by cbarto11** [comment]
done.
be63e2cc761f082bfa8df0ff092dc300af932b23
250fcd6c1f16fe03d573396e3a53b8c6e4a6b303
088784e4458e824cc02d0e539537dce5ebd83bb8
