### ISSUE TITLE
Site description not being added to new profile sites

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#39]
Site description not being added to new profile sites.

**Comment by marpa** [comment]
The UNCC version of the Batch Create plugin was activated, as well as the description fix and force update plugins...

**Comment by marpa** [comment]
needs more testing to confirm if an issue

**Comment by marpa** [comment]
Have confirmed this is an issue even when the Batch Create - Description fix is activated.

Also discovered that the site_path with no specified domain is appending https when building domain

**Comment by cbarto11** [comment]
0580ade1e2139535bb3b6a60a2affc25a221e393
