### ISSUE TITLE
Store profile site data in custom user field (profile_site) and NOT in the WP website field

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#40]
Save org user data to their wp user profile:
user description > Biographical Info
user profile site url > Website

Add custom user fields for:
user connection post url > custom user field
user category > custom user field
user type > custom user field

For more information on adding custom fields to user profiles, see:
http://wpengineer.com/2173/custom-fields-wordpress-user-profile/

For view user profiles, see:
wp-admin/network/user-edit.php

**Comment by marpa** [comment]
Might even be able to save their status in a custom user profile field...  Then we might not even needs the orghub_user table....

**Comment by marpa** [comment]
Update:
Do NOT use existing Biographical Info field for user description (i.e. position title in our instance).  Create a new custom field:
user description > custom field

Make all custom fields read only

**Comment by marpa** [comment]
Store profile site data in custom user field (profile_site) and NOT in the WP website field

**Comment by cbarto11** [comment]
7f2eaba4d5d3f86ad93ae519bcd8541e7cf8996b
