### ISSUE TITLE
Error when creating the 2nd profile site in a session

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#46]
When processing all users from a list of new users, when code trys to create the 2nd profile site, there is the following error:
> Fatal error: Cannot redeclare class NBT_Template_copier in /srv/www/clasincubatorwp/public_html/wp-content/plugins/blogtemplates/blogtemplatesfiles/copier.php on line 5

No additional profile sites can be created after this error.  For testing data, see:
[CLAS Pages Org Hub Data](https://docs.google.com/a/uncc.edu/spreadsheets/d/1cUUJlPdwQ1ZNroSLK9_HQuvT0naNTt8R30_sl_OaAaI/edit#gid=637028212)

**Comment by cbarto11** [comment]
This is a bug in the blog templates plugin.  I cannot fix it without altering the blog templates plugin.

**Comment by cbarto11** [comment]
fixed in blog templates plugin.
