### ISSUE TITLE
Error when processing batch upload items

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#52]
When attempting to "process" items in the Upload Batch List, items do NOT get processed and the following error occurs:
> Warning: Invalid argument supplied for foreach() in /home/cpagest/public_html/wp-content/plugins/organization-hub/classes/model/upload-model.php on line 774
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/cpagest/public_html/wp-content/plugins/organization-hub/classes/model/upload-model.php:774) in /home/cpagest/public_html/wp-includes/pluggable.php on line 1178

**Comment by marpa** [comment]
items do get processed even after this error

**Comment by cbarto11** [comment]
fixing issue #53 will fix this error.

**Comment by cbarto11** [comment]
fixed issue #53.
