### ISSUE TITLE
Fatal error viewing admin pages

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#54]
Latest version causes following error when viewing admin pages:

> Fatal error: Only variables can be passed by reference in /home/cpagest/public_html/wp-content/plugins/organization-hub/classes/model/model.php on line 292

See: https://clas-pages-test.uncc.edu/wp-admin/network/admin.php

**Comment by cbarto11** [comment]
9d614324683742dd71c36c3dd6833e7775dd1ebe
