### ISSUE TITLE
Sites list not updating

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#55]
The sites list does not get updating when clicking on the "Refresh Sites" button.  Instead, nothing happens.  

* dev, preprod and pages.uncc.edu are running same version of org hub
* Listing refresh is working on preprod, but is NOT working on dev or on pages.uncc.edu
* Listing refresh is also working on clas-pages.uncc.edu, but this is an earlier version

**Comment by marpa** [comment]
pages.uncc.edu generates following error:
> Mixed Content: The page at 'https://pages.uncc.edu/wp-admin/network/admin.php?page=orghub-sites&tab=list' was loaded over HTTPS, but requested an insecure script 'http://pages.uncc.edu/'. This request has been blocked; the content must be served over HTTPS.

dev does NOT generates a similar error....

**Comment by cbarto11** [comment]
5a2d527f216e0a186d73eb537dbb0a9a0ee84915
