### ISSUE TITLE
Error messages when using bulk upload to add users 

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#60]
When using bulk upload type = user, action = add, the following error occurs:

Warning: Invalid argument supplied for foreach() in /home/pages2/public_html/wp-content/plugins/organization-hub/classes/model/upload-model.php on line 3191

The user is correctly added to site specified

**Comment by cbarto11** [comment]
021a48babca0e0da6bc078071008a26ea8f5e71d
