### ISSUE TITLE
WordPress profile connection link incorrect

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#63]
The Connection Post link in that the org hub adds to user profiles is incorrect.  Specifically, it includes "blog" in the url path.

In order for this link to work properly, org hub may need to know about the connections hub permalink structure...

**Comment by atrus1701** [comment]
39f6d72264b26e123e946ff3f1dbb24627d62aca
188dea03cc9e68f7be7b7499cc505e8a28c01980
