### ISSUE TITLE
Maximum execution time exceeded when processing users

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#66]
Running "process all users" after uploading a new csv file of users was only able to create new users on 1st run.  Profile sites and connections posts were NOT created.

Was able to create user and accounts and profile sites for new users by selecting all new users and choosing 1st "create user accounts" and then "create profile sites"

I think it was after creating user accounts, that I got the following error:
>Fatal error: Maximum execution time of 30 seconds exceeded in /home/pages2/public_html/wp-content/plugins/organization-hub/classes/model/users-model.php on line 2228

In order to create connection posts, I had to look up each new user and add connection posts via their edit screen

**Comment by atrus1701** [comment]
0c2ae9711dd7e54fc928b12deb58014bdd9847d7
