### ISSUE TITLE
Batch Upload to sites with secondary domain names

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#69]
Not able to add users to a site that has a multi-domain mapped domain.  

It may be that all batch upload types need to include a domain field.  If no value is specified, then it will use the primary domain.

**Comment by marpa** [comment]
When I tried to add users via the network admin batch upload, the error was:
> cannot switch to <<site-name>>

When I tried to add users via the site's batch upload, items were processed w/o error, but changes were not made...

**Comment by atrus1701** [comment]
0029f37a5e74c1b1225658d6448ebe61dbabfc72
Need to test.

**Comment by marpa** [comment]
Have tested this new code on pages.uncc.edu.
Works for sites that use the primary domain (i.e. pages.uncc.edu)
Does NOT work for sites that use a secondary domain.  Error is:
>add user error: Unable to find site: <<slug>>

For testing, see: https://goo.gl/QY7Ej0

**Comment by atrus1701** [comment]
f91873065166071ed0cab6b5e9934ae53e7fa3b6
Tested with the CSV from google.  I was added to the connections site, but not frneale.
Looking into that.

**Comment by atrus1701** [comment]
Found that the code is getting to the command: add_user_to_blog
The user id, blog id, and role passed into the function are correct and the function is returning success despite the fact that my username is not added to the blog.  It may be an issue with me being a Super Admin.

**Comment by marpa** [comment]
I just added another non-super admin user to the testing csv file.  Maybe see if that user is added. see: https://goo.gl/QY7Ej0

**Comment by marpa** [comment]
This has been tested and seems to work.
