### ISSUE TITLE
Last listing data not displayed

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#71]
The date that the Sites List was refreshed is NOT being displayed, see:
https://clas-pages.uncc.edu/wp-admin/network/admin.php?page=orghub-sites

After refreshing sites on CLAS Pages, message displayed is:
> The sites lists has never been cached.

After refreshing sites on UNC Charlotte Pages, message indicates an earlier refresh date:
> The last sites listing refresh happened on 2015-09-14 21:21:12.

(UNC Charlotte Pages does NOT seem to be updating even after refreshing... Earlier issues with this were resolved by updating the APL plugin)

**Comment by atrus1701** [comment]
Fixed by an issue that was fixed in the APL plugin.
