### ISSUE TITLE
User import status not working

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#74]
Org Hub users were imported into PROD using the following data, see:
[Org Hub Users 3-15-2016](https://docs.google.com/spreadsheets/d/1c5Gsbids_0HWA8yrI7Ypcp5MZlfW3I1lDv9-jNVldOs/edit#gid=258730960)

Initial status indicated that users that were active and inactive.  After all users were processed, all users status was changed to "new", see:
https://pages.uncc.edu/wp-admin/network/admin.php?page=orghub-users&tab=list

**Comment by marpa** [comment]
The above is incorrect.  All user status after processing users was set to "active" (not "new") including users who were imported as "inactive"  

Users were imported using the "add" option.  Maybe users should have been imported using "sync"?

**Comment by atrus1701** [comment]
This was due to the codebase on production being old.  This was fixed with an update.
