### ISSUE TITLE
Edit org hub users status 

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#76]
It would be good to have an option to edit the status of an org hub user.  In particular, it would be good to be able to change the status from active to inactive.  In addition, it might be useful to be able to delete an org hub user.

**Comment by atrus1701** [comment]
What do you mean by delete?  Do you mean set as inactive?

**Comment by marpa** [comment]
Need to be able to change the status of users via the admin UI and via csv import.  Should have admin options for de-activate and activate user.  CSV importer should look at the status field and update the user status based on its value

It would also be good to be able to delete users from org hub user table completely.

**Comment by akforsyt** [comment]
closed by 9249d9a42e94707650c82db89d3fb2eed9544966
