### ISSUE TITLE
Add taxonomy batch upload action not working for custom taxonomies

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#77]
Add taxonomy batch upload action not working for custom taxonomies.

**Comment by atrus1701** [comment]
Like the custom post type issue, custom taxonomies are loaded on the individual blogs, not in the network admin. To do this, we would need to create a AJAX call to the individual blog that runs upload action at the blog-level, not the network admin level.

**Comment by marpa** [comment]
Let's revisit implementing this for network admin batch uploads and focus on getting to work for site level batch uploads

**Comment by clas-web** [comment]
Will address in future releases
