### ISSUE TITLE
Add taxonomy batch upload action support for custom post types

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#78]
Add taxonomy batch upload action support only works for posts.  Would be good if also worked with custom post types

**Comment by atrus1701** [comment]
This is due to the fact that custom post types are loaded on the individual blogs, not in the network admin.  To do this, we would need to create a AJAX call to the individual blog that runs upload action at the blog-level, not the network admin level.

**Comment by marpa** [comment]
Ok, let's revisit this issue in the future for network admin batch upload.  Can this be implemented for site level batch upload?
