### ISSUE TITLE
Add settings for Shib authentication

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#79]
Add settings for shib authentication.  Then add conditional code for adding new users to all functions that create users (Users > Create User Account, Batch Upload > Add User) that adds new users along with the user meta info the Shib plugin needs.

**Comment by atrus1701** [comment]
Added through the Shibboleth Helper plugin which needs to be tested.

**Comment by akforsyt** [comment]
Is this still relevant with the way we are using shib?

**Comment by marpa** [comment]
Update Org Hub create user model to add meta-data about Shib

**Comment by akforsyt** [comment]
closed by 9249d9a42e94707650c82db89d3fb2eed9544966
