### ISSUE TITLE
Commas in category import needs to be escaped

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#81]
When there is a comma in a category name in the user upload csv, it should be treated as one category

**Comment by atrus1701** [comment]
I would need to look at your CSV, but I believe you are not properly escaping your comma the category name.  There is no way for the program to know if a comma is part of category vs. a separator if not properly escaped.

**Comment by marpa** [comment]
Looks like WordPress has issues with commas in taxonomy terms, see:
https://core.trac.wordpress.org/ticket/14691

**Comment by akforsyt** [comment]
Not likely to be ever be remedied in WP.
