### ISSUE TITLE
Connections posts created from user import have wrong titles

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#82]
Connections posts created from user import have titles that are derived from first and last name instead of what is specified in the site_path column.  To test, see:
[UNC Charlotte Faculty Sites > import test](https://docs.google.com/spreadsheets/d/1TLJW2YwIGGaUabfpQ93eVWNdpyiIUCBZO7K4AZB5VfM/edit#gid=699093359)

**Comment by atrus1701** [comment]
Done.
8216947c8ff0249d28b7f065258d40c94e290671
