### ISSUE TITLE
Shib User Update

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#84]
Create a plugin that will add Shib meta values to all LDAP users.  Ideally, this plugin could be run from the network admin UI as needed.  

Use case would be an organization that wants to gradually transition from LDAP authentication to Shib.

**Comment by atrus1701** [comment]
Part of the Shibboleth Helper plugin that needs to be tested.

**Comment by akforsyt** [comment]
Is this still relevant with the way we are using shib?

**Comment by akforsyt** [comment]
closed by 9249d9a42e94707650c82db89d3fb2eed9544966
