### ISSUE TITLE
Shib compatible batch user upload

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#85]
Create a batch upload UI that site admins can use to add users to their site that is similar to the WPMU LDAP plugin batch upload, see:
https://clas-pages.uncc.edu/oat/wp-admin/users.php?page=wpmu_ldap_adduser.functions.php

Make sure all Org Hub batch upload code for users works with Shib users, see: https://github.com/clas-web/organization-hub/issues/79

**Comment by atrus1701** [comment]
Part of the Shibboleth Helper plugin that needs to be tested.

**Comment by akforsyt** [comment]
Is this still relevant with the way we are using shib?

**Comment by akforsyt** [comment]
closed by 9249d9a42e94707650c82db89d3fb2eed9544966
