### ISSUE TITLE
Batch Upload: post titles with single quote cause import errors

### ISSUE THREAD

**Issue by clas-web** [clas-web/organization-hub#86]
Post titles with single quote cause import errors.  If there are then one post with the same title, other errors could result...

Might be better to allow items to be imported based on post_name (i.e. slug) since slugs are always unique...  Alternatively code could allow either post_title or post_name...

**Comment by marpa** [comment]
To test, import the following file: 
[spivak wp-csv export > test-import](https://docs.google.com/spreadsheets/d/1yfy3Uc99n_Q--vrdHsMziAxBT-hm3P3CBlHhEdCF-Pc/edit#gid=1577682014)

into the following site, see: 
https://devpages.uncc.edu/spivack/wp-admin/admin.php?page=orghub-upload

**Comment by marpa** [comment]
This error was caused by the WP CSV import plugin adding html-encoding to post titles.
