### ISSUE TITLE
Parent field not working

### ISSUE THREAD

**Issue by marpa** [clas-web/organization-hub#88]
Batch Upload: When adding a page and specifying the parent of that page, the page is added but the specified parent is NOT set properly.

**Comment by marpa** [comment]
Here is link to documentation of this, see: [Batch Upload > type > page](https://github.com/clas-web/organization-hub/wiki/Batch-Upload#type-page)

**Comment by akforsyt** [comment]
closed by 9249d9a42e94707650c82db89d3fb2eed9544966
